#!/usr/bin/env bash
# Install nginx on the web server, nginx should listen on port 80

# Update apt repository and install nginx
sudo apt update
sudo apt-get install -y nginx

# Configure 'Hello World!' page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Reload the nginx configuration.
sudo pkill -HUP nginx
