#!/usr/bin/env bash
# Set up redirection to another page

# Make sure nginx is installed
sudo apt-get update
sudo apt install -y nginx

# backup default configuration
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

# Replace location block with redirect block
sudo sed -i '/location \/ {/,/}/c\    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

# Reload configuration
sudo service nginx restart
