#!/usr/bin/env bash
# Set up redirection to another page

link="https://www.youtube.com/watch?v=QH2-TGUlwu4"

echo "Hello World!" | sudo tee /etc/nginx/html/index.html
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/err_404.html

printf %s "server {
       listen 80;
       listen [::]:80 default_server;

       root /etc/nginx/html;
       index index.html;

       location /redirect_me {
           return 301 $link;
       }

       error_page 404 /err_404.html;
       location /404 {
           root /etc/nginx/html;
	   internal;
       }
}" | sudo tee /etc/nginx/sites-available/default

# Reload configuration
sudo service nginx restart
