#!/usr/bin/env bash
# Install and configure HAProxy on the load balancer `lb-01` server

# update packages and install HAProxy
sudo apt update
sudo apt install -y haproxy

# setup HAProxy configuration
cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg
frontend web-frontend
	    bind *:80
	    default_backend web-backend

backend web-backend
        balance roundrobin
	    server web-01 18.209.152.248:80 check
	    server web-02 54.157.179.19:80 check

EOL

# restart HAProxy configuration
sudo service haproxy restart
