#!/usr/bin/env bash
# generate a backup file for mysqldump

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <mysql_password>"
    exit 1
fi

mysqldump -uroot -p"$1" --all-databases > backup.sql

# Compress backup
DATE=$(date +"%d-%m-%Y")
tar -czvf "$DATE.tar.gz" backup.sql
