#!/usr/bin/env bash
# create a file that should contain its PID, displays 'To infinity
# and beyond indefinitely, displays 'I hate the kill command' when
# receiving a SIGTERM signal, 'Y U no love me?!' when receiving a
# SIGINT signal, and deletes the file and terminates on SIGQUIT or
# SIGTERM signal

echo "$$" > /var/run/myscript.pid

trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit;' SIGTERM
trap 'echo -e "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT

while true
do
    echo To infinity and beyond
    sleep 2
done
