#!/usr/bin/env bash
# display the content of the file /etc/passwd
# the script should only display the username, id and home path

while read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < /etc/passwd
