#!/usr/bin/env bash
# Use a while loop to print 'Best School' 10 times, and prints 'Hi'
# on the 9th iteration

i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i == 9 ]
    then
	echo Hi
    fi
    (( i += 1 ))
done
