#!/usr/bin/env bash
# loop from 1 to 10, display 'bad luck' on the 4th iteration, 'good
# luck' on the 8th iteration and 'Best School' for the rest
i=1
while [ $i -le 10 ]
do
    if [ $i == 4 ]
    then
	echo "bad luck"
    elif [ $i == 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    (( i += 1 ))
done
