#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes: hours from 0-12
# and minutes from 1 - 59

hour=0
min=1

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	(( hour += 1 ))
	while [ $min -le 59 ]
	      do
		  echo $min
		  (( min += 1 ))
	done
	min=1
done
