#!/usr/bin/env bash
# Run nginx as the nginx user short fix
pkill apache2
sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-available/default
echo "user nginx;" | cat - /etc/nginx/nginx.conf > temp && mv temp /etc/nginx/nginx.conf
service nginx restart
