#!/usr/bin/env bash
# Run nginx as the nginx user short fix
sudo pkill apache2
sudo sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-available/default
sudo chmod 0644 /etc/nginx/nginx.conf
sudo service nginx restart
